### ISSUE TITLE
Can't get it working

### ISSUE THREAD

**Issue by janfelhut04** [LeoKle/Euroscope-SIM-Generator#9]
Hello! I find your plugin really amazing and tried to test it, but didnt get it working. Firstly some .csv files are missing and then other messages show up and it doesnt work. Any known issues on these?

**Comment by LeoKle** [comment]
Hi,

just to confirm. This repo is a standalone .EXE which creates sim files (.txt) for Euroscope. Not a DLL you can load in Euroscope.
Required is the airports.json which defines runways, SIDs, STARs etc. and a CSV which defines callsign, aircraft type, ADEP, ADES

I was not allowed to upload the CSVs due to copyright, but they follow this schema.

| Callsign | Assigned Departure Aerodrome (ADES) | Assigned Destination Aerodrome (ADEP) | Aircrafttype + Waketurbulence Category |
| - | :-: | :-: | :-: |
| DLH123 | CYHZ | EDDK | B763/H |

The file has to be named like the airport ICAO.

If you'd like a guide on how to use it or require more information let me know. I currently have a guide, but only in German, which I could quickly translate.

**Comment by janfelhut04** [comment]
Ah okay. Hab schon verstanden das es ein standalone ist. Hatte aber probleme da ich es mit der CSV file nicht ganz gepeilt hab :D Wurde aber liebend gerne die guide auf Deutsch anschauen!

**Comment by LeoKle** [comment]
Guide in German: https://docs.google.com/document/d/1pUlUwF_YzQeFBgkizXoxCgyhRWSexjYoCTuSdaCMQXg/edit?usp=sharing

**Comment by janfelhut04** [comment]
Perfect thanks
